### PR TITLE
Support for assuming roles in S3A filesystem

### PR DESCRIPTION
**Pull request by jasonslepicka**

### CODE REVIEW

**Comment by jasonslepicka** [comment]
Don't try to build the whole thing.  
In hadoop-tools/hadoop-aws, run mvn package

This will build hadoop-aws-2.7.1.jar

For this to work, you need hadoop 2.7.1.  

Replace hadoop-2.7.1/share/hadoop/tools/lib/hadoop-aws-2.7.1.jar

Make sure that the jar is added to classpath.  This should be done on DET already in spark-defaults.conf, but DET is using hadoop 2.6.0.  Need to change that.  

Add following properties to core-site.xml
```
 <property>
  <name>fs.s3a.alternate.role.access.key</name>
  <value></value>
 </property>
 <property>
  <name>fs.s3a.alternate.role.secret.key</name>
  <value></value>
 </property>
 <property>
  <name>fs.s3a.alternate.role.arn</name>
  <value></value>
 </property>
 <property>
  <name>fs.s3a.alternate.role.external.id</name>
  <value></value>
 </property>
```

Run the following commands to verify we can read from customer bucket and our bucket.
```
./spark-shell --packages com.amazonaws:aws-java-sdk:1.10.48 --master yarn-client
 sc.textFile("s3a://ds12-education/clickstream-challenge/data/users.tsv.gz").count()
sc.textFile("s3a://pluto-dw-nginx-collector-logs/2016/04/01/00/00/2b0d7720-4e9e-42c4-a13d-e73a10338ddf-access.log-2016-04-01-1459468801.gz").count()
```

**Comment by hcavalle** [comment]
When using the modified `hadoop-aws` jar on DET to access either s3 path (ours and theirs):
```
java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManagerConfiguration.setMultipartUploadThreshold(J)V
        at org.apache.hadoop.fs.s3a.S3AFileSystem.subInitialize(S3AFileSystem.java:330)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:189)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2596)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:256)
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:199)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
        at scala.Option.getOrElse(Option.scala:120)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1143)
```
Same error either way. 

when switching back to unmodified hadoop-aws jar pulling in from our bucket works fine while we get the expected access denied error when trying to access the client bucket. 

I'll double check that I didn't mess anything up in the process.

**Comment by jasonslepicka** [comment]
Are you running pyspark with the newer version of the aws sdk as an argument in packages and removing the old version from the spark defaults?

**Comment by hcavalle** [comment]
This is working now! :bear:

**Pull request merged**
